language: erlang

env:
   - ST=PharoCore-1.3
   - ST=Pharo-1.4
   - ST=Pharo-2.0 
#   - ST=Pharo-3.0

# blacklist master as it is the "shared code" branch
branches:
  except:
    - master

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $BUILDER_CI_HOME/testTravisCI.sh  # -verbose
