private html
standardPageHeader
	^ '<head>
<title>Shared Smalltalk Workspace {1} - http://ws.stfx.eu/{1}</title>
<link href="http://stfx.eu/wws/style.css" rel="stylesheet" type="text/css"/>
<script src="http://stfx.eu/wws/highlight/highlight.pack.js" type="text/javascript"></script>
<script type="text/javascript">
  hljs.initHighlightingOnLoad();
</script>
<link href="http://stfx.eu/wws/highlight/styles/default.css" rel="stylesheet"" type="text/css"/>
</head>
'