private html
standardPageProlog
	^ '<h1>Shared Smalltalk Workspace {1}<h1>
<h3><a href="{1}">http://ws.stfx.eu/{1}</a></h3>
<div class="toolbar">
Doit <input class="doit" type="text" value="ZnWorkspace openUrl: ''http://ws.stfx.eu/{1}''." size="60" readonly="true"/>
| <a href="http://ws.stfx.eu/{1}?format=text">Raw</a>
| For instructions, see the <a href="http://ws.stfx.eu/1WS4U">Getting Started Workspace</a>
| <a href="http://ws.stfx.eu">Home</a>
</div>
'