private html
standardPageFooter
	^ '<div class="footer">
<a href="http://ws.stfx.eu">Shared Smalltalk Workspaces</a>
 is a free web service offered by
<a href="http://stfx.eu">http://stfx.eu</a>. 
Copyright &copy; 2012,2013 Sven Van Caekenberghe.
Built and served using <a href="http://www.pharo.st">Pharo Smalltalk</a> 2.0.
</div>
<div class="disclaimer">
THIS SOFTWARE SERVICE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHOR OR SERVICE PROVIDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE SERVICE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE SERVICE.
</div>'